packages:
  - packages/*
  - templates/*
  - templates/*/functions
  - tests/*
  - sites/*
  - sites/*/functions

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - "@firebase/util"

ignoredBuiltDependencies:
  - re2
