import type { Data } from "@puckeditor/core";
import { z } from "zod";
import { walkComponents } from "./walk.js";

/**
 * Free style (« Style » tab of the admin). Each section may carry a reserved `_style` prop:
 *
 * ```json
 * { "section": { "base": { "paddingTop": "96px" }, "mobile": { "paddingTop": "48px" } },
 *   "fields": { "title": { "base": { "color": "#0f1e33", "fontSize": "56px" } } } }
 * ```
 *
 * Keys of `fields` are marker paths (`data-of`, e.g. `items.answer`): a list field is styled for
 * all its items. Values go through a whitelist (no raw CSS), and the CSS is generated by
 * {@link buildPageCss}, identically in the editor and on the published site.
 */
export const STYLE_KEY = "_style";

export type Breakpoint = "base" | "tablet" | "mobile";

export const BREAKPOINTS: Breakpoint[] = ["base", "tablet", "mobile"];

/** Upper bound (inclusive, in CSS pixels) of each smaller screen. */
export const BREAKPOINT_MAX_WIDTH = { tablet: 1023, mobile: 767 } as const;

/** Screen of a given viewport width. */
export function breakpointForWidth(width: number): Breakpoint {
  if (width <= BREAKPOINT_MAX_WIDTH.mobile) return "mobile";
  if (width <= BREAKPOINT_MAX_WIDTH.tablet) return "tablet";
  return "base";
}

const HEX = /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const TOKEN_COLOR = /^var\(--color-[a-z0-9-]{1,40}\)$/;
const FONT = /^(?:var\(--font-[a-z0-9-]{1,40}\)|sans-serif|serif|monospace|system-ui)$/;
const LENGTH = /^-?(?:\d{1,4}(?:\.\d{1,3})?|\.\d{1,3})(?:px|rem|em|%|vw|vh)$/;
// Firebase Storage download URLs, the emulator, or files of the site (`/images/a.webp`). No
// quote, parenthesis, backslash or space can get through, so `url("…")` cannot be escaped.
const URL =
  /^(?:https?:\/\/[A-Za-z0-9.-]{1,253}(?::\d{1,5})?)?\/[A-Za-z0-9/_\-.~%]{0,2000}(?:\?[A-Za-z0-9_\-.~%=&]{0,2000})?$/;

const color = z
  .string()
  .refine((v) => HEX.test(v) || TOKEN_COLOR.test(v) || v === "transparent" || v === "currentColor");
const length = (extra: string[] = []) =>
  z.string().refine((v) => v === "0" || LENGTH.test(v) || extra.includes(v));
const positive = (extra: string[] = []) =>
  z
    .string()
    .refine((v) => v === "0" || (LENGTH.test(v) && !v.startsWith("-")) || extra.includes(v));

const SHADOWS = {
  none: "none",
  sm: "0 1px 3px rgb(0 0 0 / 0.12)",
  md: "0 10px 30px -10px rgb(0 0 0 / 0.3)",
  lg: "0 30px 80px -20px rgb(0 0 0 / 0.45)",
} as const;

/** Whitelisted style properties. */
export const styleValuesSchema = z.object({
  // Typography
  color: color.optional(),
  fontFamily: z.string().regex(FONT).optional(),
  fontSize: positive().optional(),
  fontWeight: z.number().int().min(100).max(900).multipleOf(100).optional(),
  lineHeight: z.number().min(0.5).max(4).optional(),
  letterSpacing: length().optional(),
  textAlign: z.enum(["left", "center", "right", "justify"]).optional(),
  textTransform: z.enum(["none", "uppercase", "lowercase", "capitalize"]).optional(),
  fontStyle: z.enum(["normal", "italic"]).optional(),
  textDecoration: z.enum(["none", "underline", "line-through"]).optional(),
  // Background
  backgroundColor: color.optional(),
  backgroundImage: z.string().regex(URL).optional(),
  backgroundSize: z.enum(["cover", "contain", "auto"]).optional(),
  backgroundPosition: z.enum(["center", "top", "bottom", "left", "right"]).optional(),
  overlayColor: color.optional(),
  overlayOpacity: z.number().min(0).max(1).optional(),
  // Spacing and size
  marginTop: length(["auto"]).optional(),
  marginBottom: length(["auto"]).optional(),
  paddingTop: positive().optional(),
  paddingRight: positive().optional(),
  paddingBottom: positive().optional(),
  paddingLeft: positive().optional(),
  maxWidth: positive(["none"]).optional(),
  minHeight: positive().optional(),
  // Border and effects
  borderWidth: positive().optional(),
  borderStyle: z.enum(["solid", "dashed", "dotted", "none"]).optional(),
  borderColor: color.optional(),
  borderRadius: positive().optional(),
  opacity: z.number().min(0).max(1).optional(),
  shadow: z.enum(["none", "sm", "md", "lg"]).optional(),
  objectFit: z.enum(["cover", "contain", "fill"]).optional(),
  // Visibility
  hidden: z.boolean().optional(),
});

export type StyleValues = z.infer<typeof styleValuesSchema>;
export type StyleProperty = keyof StyleValues;
export type ResponsiveStyle = Partial<Record<Breakpoint, StyleValues>>;

export interface SectionStyle {
  /** Root element of the section. */
  section?: ResponsiveStyle;
  /** Elements of the section, by marker path (`title`, `items.answer`, `image`…). */
  fields?: Record<string, ResponsiveStyle>;
}

export const STYLE_PROPERTIES = Object.keys(styleValuesSchema.shape) as StyleProperty[];

/** Properties applied to the text itself (its marker); the others go to its element. */
const INLINE: ReadonlySet<StyleProperty> = new Set<StyleProperty>([
  "color",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "letterSpacing",
  "textTransform",
  "fontStyle",
  "textDecoration",
]);

const ID = /^[A-Za-z0-9_-]{1,120}$/;
const PATH = /^[A-Za-z0-9_]{1,60}(?:\.[A-Za-z0-9_]{1,60}){0,5}$/;

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Keeps the valid properties of one breakpoint (invalid ones are dropped, not the whole set). */
function sanitizeValues(value: unknown): StyleValues | undefined {
  if (!isObject(value)) return undefined;
  const out: Record<string, unknown> = {};
  for (const key of STYLE_PROPERTIES) {
    if (value[key] === undefined) continue;
    const parsed = styleValuesSchema.shape[key].safeParse(value[key]);
    if (parsed.success && parsed.data !== undefined) out[key] = parsed.data;
  }
  return Object.keys(out).length > 0 ? (out as StyleValues) : undefined;
}

function sanitizeResponsive(value: unknown): ResponsiveStyle | undefined {
  if (!isObject(value)) return undefined;
  const out: ResponsiveStyle = {};
  for (const bp of BREAKPOINTS) {
    const values = sanitizeValues(value[bp]);
    if (values) out[bp] = values;
  }
  return Object.keys(out).length > 0 ? out : undefined;
}

/** Returns the valid part of a `_style` value, or `undefined` when nothing valid remains. */
export function sanitizeStyle(value: unknown): SectionStyle | undefined {
  if (!isObject(value)) return undefined;
  const out: SectionStyle = {};
  const section = sanitizeResponsive(value.section);
  if (section) out.section = section;
  if (isObject(value.fields)) {
    const fields: Record<string, ResponsiveStyle> = {};
    for (const [path, style] of Object.entries(value.fields)) {
      if (!PATH.test(path)) continue;
      const clean = sanitizeResponsive(style);
      if (clean) fields[path] = clean;
    }
    if (Object.keys(fields).length > 0) out.fields = fields;
  }
  return out.section || out.fields ? out : undefined;
}

/** Copy of the page data where every `_style` is sanitized (or removed when invalid). */
export function sanitizePageStyles(data: Data): Data {
  const copy = structuredClone(data) as Data;
  walkComponents(copy, (item) => {
    const props = item.props as Record<string, unknown>;
    if (!(STYLE_KEY in props)) return;
    const clean = sanitizeStyle(props[STYLE_KEY]);
    if (clean) props[STYLE_KEY] = clean;
    else delete props[STYLE_KEY];
  });
  return copy;
}

function declarations(values: StyleValues, keys: StyleProperty[], editing: boolean): string[] {
  const out: string[] = [];
  const has = (key: StyleProperty) => keys.includes(key) && values[key] !== undefined;
  const push = (prop: string, value: string | number) => out.push(`${prop}:${value}`);
  if (has("color")) push("color", values.color!);
  if (has("fontFamily")) push("font-family", values.fontFamily!);
  if (has("fontSize")) push("font-size", values.fontSize!);
  if (has("fontWeight")) push("font-weight", values.fontWeight!);
  if (has("lineHeight")) push("line-height", values.lineHeight!);
  if (has("letterSpacing")) push("letter-spacing", values.letterSpacing!);
  if (has("textAlign")) push("text-align", values.textAlign!);
  if (has("textTransform")) push("text-transform", values.textTransform!);
  if (has("fontStyle")) push("font-style", values.fontStyle!);
  if (has("textDecoration")) push("text-decoration-line", values.textDecoration!);
  if (has("backgroundColor")) push("background-color", values.backgroundColor!);
  if (has("backgroundImage")) {
    const layers = [`url("${values.backgroundImage}")`];
    if (values.overlayColor && (values.overlayOpacity ?? 0.5) > 0) {
      const pct = Math.round((values.overlayOpacity ?? 0.5) * 100);
      const veil = `color-mix(in srgb,${values.overlayColor} ${pct}%,transparent)`;
      layers.unshift(`linear-gradient(${veil},${veil})`);
    }
    push("background-image", layers.join(","));
    push("background-size", values.backgroundSize ?? "cover");
    push("background-position", values.backgroundPosition ?? "center");
    push("background-repeat", "no-repeat");
  } else {
    if (has("backgroundSize")) push("background-size", values.backgroundSize!);
    if (has("backgroundPosition")) push("background-position", values.backgroundPosition!);
  }
  if (has("marginTop")) push("margin-top", values.marginTop!);
  if (has("marginBottom")) push("margin-bottom", values.marginBottom!);
  if (has("paddingTop")) push("padding-top", values.paddingTop!);
  if (has("paddingRight")) push("padding-right", values.paddingRight!);
  if (has("paddingBottom")) push("padding-bottom", values.paddingBottom!);
  if (has("paddingLeft")) push("padding-left", values.paddingLeft!);
  if (has("maxWidth")) push("max-width", values.maxWidth!);
  if (has("minHeight")) push("min-height", values.minHeight!);
  if (has("borderWidth")) {
    push("border-width", values.borderWidth!);
    push("border-style", values.borderStyle ?? "solid");
  } else if (has("borderStyle")) push("border-style", values.borderStyle!);
  if (has("borderColor")) push("border-color", values.borderColor!);
  if (has("borderRadius")) push("border-radius", values.borderRadius!);
  if (has("opacity")) push("opacity", values.opacity!);
  if (has("shadow")) push("box-shadow", SHADOWS[values.shadow!]);
  if (has("objectFit")) push("object-fit", values.objectFit!);
  if (has("hidden") && values.hidden) {
    // In the editor, a hidden element stays visible (faded) so it can still be selected.
    if (editing) {
      push("opacity", 0.35);
      push("outline", "2px dashed #94a3b8");
    } else push("display", "none");
  } else if (has("hidden")) {
    // `false` on a smaller screen shows what a larger one hides: back to the site's own CSS.
    if (editing) {
      if (values.opacity === undefined) push("opacity", "revert-layer");
      push("outline", "revert-layer");
    } else push("display", "revert-layer");
  }
  return out;
}

function rule(selectors: string[], decls: string[]): string {
  return decls.length > 0 ? `${selectors.join(",")}{${decls.join(";")}}` : "";
}

/** CSS rules of one section for one breakpoint. */
function sectionRules(id: string, style: SectionStyle, bp: Breakpoint, editing: boolean): string[] {
  const out: string[] = [];
  const scope = `[data-of-s="${id}"]`;
  // Elements of sections nested in this one (slots) are not this section's.
  const own = `:not(${scope} [data-of-s] *)`;
  const section = style.section?.[bp];
  if (section) out.push(rule([`${scope}>*`], declarations(section, STYLE_PROPERTIES, editing)));
  for (const [path, responsive] of Object.entries(style.fields ?? {})) {
    const values = responsive[bp];
    if (!values) continue;
    const media = `${scope} :is(img,video)[data-of="${path}"]${own}`;
    const text = `${scope} :not(img,video)[data-of="${path}"]${own}`;
    const element = `${scope} :has(>:not(img,video)[data-of="${path}"])${own}`;
    const inline = STYLE_PROPERTIES.filter((key) => INLINE.has(key));
    const box = STYLE_PROPERTIES.filter((key) => !INLINE.has(key));
    out.push(rule([media, text], declarations(values, inline, editing)));
    out.push(rule([media, element], declarations(values, box, editing)));
  }
  return out.filter(Boolean);
}

/**
 * Stylesheet of a page from the `_style` of its sections: base rules, then tablet and mobile
 * overrides in media queries. Pure and deterministic; unsafe values and ids are ignored.
 */
export function buildPageCss(data: Data, options: { editing?: boolean } = {}): string {
  const editing = options.editing === true;
  const rules: Record<Breakpoint, string[]> = { base: [], tablet: [], mobile: [] };
  walkComponents(data, (item) => {
    const props = item.props as Record<string, unknown>;
    const id = props.id;
    if (typeof id !== "string" || !ID.test(id) || props[STYLE_KEY] === undefined) return;
    const style = sanitizeStyle(props[STYLE_KEY]);
    if (!style) return;
    for (const bp of BREAKPOINTS) rules[bp].push(...sectionRules(id, style, bp, editing));
  });
  const css = [...rules.base];
  if (rules.tablet.length > 0)
    css.push(`@media (max-width:${BREAKPOINT_MAX_WIDTH.tablet}.98px){${rules.tablet.join("")}}`);
  if (rules.mobile.length > 0)
    css.push(`@media (max-width:${BREAKPOINT_MAX_WIDTH.mobile}.98px){${rules.mobile.join("")}}`);
  return css.join("\n");
}

// ---------------------------------------------------------------------------------------------
// Theme

/** Values of the theme tokens chosen by the owner, e.g. `{ "color-ink": "#101820" }`. */
export type ThemeValues = Record<string, string>;

const THEME_KEY = /^(color|font)-[a-z0-9-]{1,40}$/;

/** Keeps the valid theme values (`color-*` → colour, `font-*` → font variable or family). */
export function sanitizeTheme(values: unknown): ThemeValues {
  const out: ThemeValues = {};
  if (!isObject(values)) return out;
  for (const [key, value] of Object.entries(values).sort(([a], [b]) => a.localeCompare(b))) {
    const kind = THEME_KEY.exec(key)?.[1];
    if (typeof value !== "string" || !kind) continue;
    if (kind === "color" ? color.safeParse(value).success : FONT.test(value)) out[key] = value;
  }
  return out;
}

/** `:root` variables overriding the site's theme tokens (Tailwind v4 `--color-*`, `--font-*`). */
export function buildThemeCss(values: unknown): string {
  const clean = sanitizeTheme(values);
  const decls = Object.entries(clean).map(([key, value]) => `--${key}:${value}`);
  return decls.length > 0 ? `:root{${decls.join(";")}}` : "";
}
